# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/OgreApp
pkgincludedir = $(includedir)/OgreApp
pkglibdir = $(libdir)/OgreApp
pkglibexecdir = $(libexecdir)/OgreApp
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = OgreBall$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in depcomp $(noinst_HEADERS) compile \
	config.guess config.sub install-sh missing ltmain.sh
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_OgreBall_OBJECTS = OgreBall-ConfigScript.$(OBJEXT) \
	OgreBall-MeshStrider.$(OBJEXT) \
	OgreBall-BaseApplication.$(OBJEXT) \
	OgreBall-OgreBallApplication.$(OBJEXT) \
	OgreBall-Physics.$(OBJEXT) OgreBall-OgreMotionState.$(OBJEXT) \
	OgreBall-GameObject.$(OBJEXT) OgreBall-OgreBall.$(OBJEXT) \
	OgreBall-Plane.$(OBJEXT) OgreBall-LevelLoader.$(OBJEXT) \
	OgreBall-MeshObject.$(OBJEXT) OgreBall-MenuActivity.$(OBJEXT) \
	OgreBall-SinglePlayerActivity.$(OBJEXT) \
	OgreBall-Interpolator.$(OBJEXT) OgreBall-Collisions.$(OBJEXT) \
	OgreBall-GoalObject.$(OBJEXT) OgreBall-Collectible.$(OBJEXT) \
	OgreBall-LevelViewer.$(OBJEXT) \
	OgreBall-DecorativeObject.$(OBJEXT) \
	OgreBall-CameraObject.$(OBJEXT) OgreBall-Sounds.$(OBJEXT) \
	OgreBall-Collidable.$(OBJEXT) \
	OgreBall-ClientPlayerActivity.$(OBJEXT) \
	OgreBall-HostPlayerActivity.$(OBJEXT) \
	OgreBall-Networking.$(OBJEXT) OgreBall-common.$(OBJEXT) \
	OgreBall-BaseMultiActivity.$(OBJEXT) \
	OgreBall-SelectorHelper.$(OBJEXT) \
	OgreBall-MovableTextOverlay.$(OBJEXT) \
	OgreBall-RectLayoutManager.$(OBJEXT) \
	OgreBall-GamecubeController.$(OBJEXT)
OgreBall_OBJECTS = $(am_OgreBall_OBJECTS)
am__DEPENDENCIES_1 =
OgreBall_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
OgreBall_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(OgreBall_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(OgreBall_SOURCES)
DIST_SOURCES = $(OgreBall_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(noinst_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/kyeh/cs/git/Super-Ogre-Ball/missing aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} /home/kyeh/cs/git/Super-Ogre-Ball/missing autoconf
AUTOHEADER = ${SHELL} /home/kyeh/cs/git/Super-Ogre-Ball/missing autoheader
AUTOMAKE = ${SHELL} /home/kyeh/cs/git/Super-Ogre-Ball/missing automake-1.14
AWK = mawk
BULLET_CFLAGS = 
BULLET_LIBS = 
CC = gcc
CCDEPMODE = depmode=gcc3
CEGUI_CFLAGS = -I/usr/include/CEGUI  
CEGUI_LIBS = -lCEGUIBase  
CEGUI_OGRE_CFLAGS = -pthread -I/usr/include/OGRE -I/usr/include/CEGUI  
CEGUI_OGRE_LIBS = -lCEGUIOgreRenderer -lOgreMain -lpthread -lCEGUIBase  
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/kyeh/cs/git/Super-Ogre-Ball/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OGRE_CFLAGS = -pthread -I/usr/include/OGRE  
OGRE_LIBS = -lOgreMain -lpthread  
OIS_CFLAGS = -I/usr/include/ois  
OIS_LIBS = -lOIS  
OTOOL = 
OTOOL64 = 
PACKAGE = OgreApp
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = :/opt/OGRE-1.8/lib/pkgconfig
RANLIB = ranlib
SDLMIXER_CFLAGS = -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDLMIXER_LIBS = -L/usr/lib/x86_64-linux-gnu -lSDL -lSDL_mixer
SDLNET_CFLAGS = -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDLNET_LIBS = -L/usr/lib/x86_64-linux-gnu -lSDL -lSDL_net
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 0.1
abs_builddir = /home/kyeh/cs/git/Super-Ogre-Ball
abs_srcdir = /home/kyeh/cs/git/Super-Ogre-Ball
abs_top_builddir = /home/kyeh/cs/git/Super-Ogre-Ball
abs_top_srcdir = /home/kyeh/cs/git/Super-Ogre-Ball
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
bullet_CFLAGS = -I/usr/include/bullet  
bullet_LIBS = -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath  
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/kyeh/cs/git/Super-Ogre-Ball/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
noinst_HEADERS = libs/ConfigLoader.hpp libs/MeshStrider.h libs/RectLayoutManager.h libs/MovableTextOverlay.h src/LevelLoader.h src/BaseApplication.h src/OgreBallApplication.h src/Physics.h src/OgreMotionState.h src/GameObject.h src/Collisions.h src/Activity.h src/MenuActivity.h src/SinglePlayerActivity.h src/Interpolator.h src/LevelViewer.h src/CameraObject.h src/Sounds.h src/ClientPlayerActivity.h src/HostPlayerActivity.h src/Networking.h src/common.h src/Leaderboard.h src/OBAnimationManager.h src/BaseMultiActivity.h src/SelectorHelper.h src/GamecubeController.h 
OgreBall_CPPFLAGS = -I$(top_srcdir) -Ilibs/OgreProcedural/include -I/usr/include/SDL2 -std=c++0x
OgreBall_SOURCES = libs/ConfigScript.cpp libs/MeshStrider.cpp src/BaseApplication.cpp src/OgreBallApplication.cpp src/Physics.cpp src/OgreMotionState.cpp src/GameObject.cpp src/OgreBall.cpp src/Plane.cpp src/LevelLoader.cpp src/MeshObject.cpp src/MenuActivity.cpp src/SinglePlayerActivity.cpp src/Interpolator.cpp src/Collisions.cpp src/GoalObject.cpp src/Collectible.cpp src/LevelViewer.cpp src/DecorativeObject.cpp src/CameraObject.cpp src/Sounds.cpp src/Collidable.cpp src/ClientPlayerActivity.cpp src/HostPlayerActivity.cpp src/Networking.cpp src/common.cpp src/BaseMultiActivity.cpp src/SelectorHelper.cpp libs/MovableTextOverlay.cpp libs/RectLayoutManager.cpp src/GamecubeController.cpp 
OgreBall_CXXFLAGS = $(OGRE_CFLAGS) $(OIS_CFLAGS) $(bullet_CFLAGS) $(SDLMIXER_CFLAGS) $(sdl_CFLAGS) $(SDLNET_CFLAGS) $(CEGUI_CFLAGS) $(CEGUI_OGRE_CFLAGS) -lboost_system -lboost_filesystem -Llibs/OgreProcedural/lib -lOgreProcedural -Wl,-rpath=libs/OgreProcedural/lib -lboost_serialization
OgreBall_LDADD = $(OGRE_LIBS) $(OIS_LIBS) $(bullet_LIBS) $(SDLMIXER_LIBS) $(CEGUI_LIBS) $(CEGUI_OGRE_LIBS) $(sdl_LIBS) $(SDLNET_LIBS)
EXTRA_DIST = buildit makeit
AUTOMAKE_OPTIONS = foreign
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

OgreBall$(EXEEXT): $(OgreBall_OBJECTS) $(OgreBall_DEPENDENCIES) $(EXTRA_OgreBall_DEPENDENCIES) 
	@rm -f OgreBall$(EXEEXT)
	$(AM_V_CXXLD)$(OgreBall_LINK) $(OgreBall_OBJECTS) $(OgreBall_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/OgreBall-BaseApplication.Po
include ./$(DEPDIR)/OgreBall-BaseMultiActivity.Po
include ./$(DEPDIR)/OgreBall-CameraObject.Po
include ./$(DEPDIR)/OgreBall-ClientPlayerActivity.Po
include ./$(DEPDIR)/OgreBall-Collectible.Po
include ./$(DEPDIR)/OgreBall-Collidable.Po
include ./$(DEPDIR)/OgreBall-Collisions.Po
include ./$(DEPDIR)/OgreBall-ConfigScript.Po
include ./$(DEPDIR)/OgreBall-DecorativeObject.Po
include ./$(DEPDIR)/OgreBall-GameObject.Po
include ./$(DEPDIR)/OgreBall-GamecubeController.Po
include ./$(DEPDIR)/OgreBall-GoalObject.Po
include ./$(DEPDIR)/OgreBall-HostPlayerActivity.Po
include ./$(DEPDIR)/OgreBall-Interpolator.Po
include ./$(DEPDIR)/OgreBall-LevelLoader.Po
include ./$(DEPDIR)/OgreBall-LevelViewer.Po
include ./$(DEPDIR)/OgreBall-MenuActivity.Po
include ./$(DEPDIR)/OgreBall-MeshObject.Po
include ./$(DEPDIR)/OgreBall-MeshStrider.Po
include ./$(DEPDIR)/OgreBall-MovableTextOverlay.Po
include ./$(DEPDIR)/OgreBall-Networking.Po
include ./$(DEPDIR)/OgreBall-OgreBall.Po
include ./$(DEPDIR)/OgreBall-OgreBallApplication.Po
include ./$(DEPDIR)/OgreBall-OgreMotionState.Po
include ./$(DEPDIR)/OgreBall-Physics.Po
include ./$(DEPDIR)/OgreBall-Plane.Po
include ./$(DEPDIR)/OgreBall-RectLayoutManager.Po
include ./$(DEPDIR)/OgreBall-SelectorHelper.Po
include ./$(DEPDIR)/OgreBall-SinglePlayerActivity.Po
include ./$(DEPDIR)/OgreBall-Sounds.Po
include ./$(DEPDIR)/OgreBall-common.Po

.cpp.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

OgreBall-ConfigScript.o: libs/ConfigScript.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-ConfigScript.o -MD -MP -MF $(DEPDIR)/OgreBall-ConfigScript.Tpo -c -o OgreBall-ConfigScript.o `test -f 'libs/ConfigScript.cpp' || echo '$(srcdir)/'`libs/ConfigScript.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-ConfigScript.Tpo $(DEPDIR)/OgreBall-ConfigScript.Po
#	$(AM_V_CXX)source='libs/ConfigScript.cpp' object='OgreBall-ConfigScript.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-ConfigScript.o `test -f 'libs/ConfigScript.cpp' || echo '$(srcdir)/'`libs/ConfigScript.cpp

OgreBall-ConfigScript.obj: libs/ConfigScript.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-ConfigScript.obj -MD -MP -MF $(DEPDIR)/OgreBall-ConfigScript.Tpo -c -o OgreBall-ConfigScript.obj `if test -f 'libs/ConfigScript.cpp'; then $(CYGPATH_W) 'libs/ConfigScript.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/ConfigScript.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-ConfigScript.Tpo $(DEPDIR)/OgreBall-ConfigScript.Po
#	$(AM_V_CXX)source='libs/ConfigScript.cpp' object='OgreBall-ConfigScript.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-ConfigScript.obj `if test -f 'libs/ConfigScript.cpp'; then $(CYGPATH_W) 'libs/ConfigScript.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/ConfigScript.cpp'; fi`

OgreBall-MeshStrider.o: libs/MeshStrider.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MeshStrider.o -MD -MP -MF $(DEPDIR)/OgreBall-MeshStrider.Tpo -c -o OgreBall-MeshStrider.o `test -f 'libs/MeshStrider.cpp' || echo '$(srcdir)/'`libs/MeshStrider.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MeshStrider.Tpo $(DEPDIR)/OgreBall-MeshStrider.Po
#	$(AM_V_CXX)source='libs/MeshStrider.cpp' object='OgreBall-MeshStrider.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MeshStrider.o `test -f 'libs/MeshStrider.cpp' || echo '$(srcdir)/'`libs/MeshStrider.cpp

OgreBall-MeshStrider.obj: libs/MeshStrider.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MeshStrider.obj -MD -MP -MF $(DEPDIR)/OgreBall-MeshStrider.Tpo -c -o OgreBall-MeshStrider.obj `if test -f 'libs/MeshStrider.cpp'; then $(CYGPATH_W) 'libs/MeshStrider.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/MeshStrider.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MeshStrider.Tpo $(DEPDIR)/OgreBall-MeshStrider.Po
#	$(AM_V_CXX)source='libs/MeshStrider.cpp' object='OgreBall-MeshStrider.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MeshStrider.obj `if test -f 'libs/MeshStrider.cpp'; then $(CYGPATH_W) 'libs/MeshStrider.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/MeshStrider.cpp'; fi`

OgreBall-BaseApplication.o: src/BaseApplication.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-BaseApplication.o -MD -MP -MF $(DEPDIR)/OgreBall-BaseApplication.Tpo -c -o OgreBall-BaseApplication.o `test -f 'src/BaseApplication.cpp' || echo '$(srcdir)/'`src/BaseApplication.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-BaseApplication.Tpo $(DEPDIR)/OgreBall-BaseApplication.Po
#	$(AM_V_CXX)source='src/BaseApplication.cpp' object='OgreBall-BaseApplication.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-BaseApplication.o `test -f 'src/BaseApplication.cpp' || echo '$(srcdir)/'`src/BaseApplication.cpp

OgreBall-BaseApplication.obj: src/BaseApplication.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-BaseApplication.obj -MD -MP -MF $(DEPDIR)/OgreBall-BaseApplication.Tpo -c -o OgreBall-BaseApplication.obj `if test -f 'src/BaseApplication.cpp'; then $(CYGPATH_W) 'src/BaseApplication.cpp'; else $(CYGPATH_W) '$(srcdir)/src/BaseApplication.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-BaseApplication.Tpo $(DEPDIR)/OgreBall-BaseApplication.Po
#	$(AM_V_CXX)source='src/BaseApplication.cpp' object='OgreBall-BaseApplication.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-BaseApplication.obj `if test -f 'src/BaseApplication.cpp'; then $(CYGPATH_W) 'src/BaseApplication.cpp'; else $(CYGPATH_W) '$(srcdir)/src/BaseApplication.cpp'; fi`

OgreBall-OgreBallApplication.o: src/OgreBallApplication.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-OgreBallApplication.o -MD -MP -MF $(DEPDIR)/OgreBall-OgreBallApplication.Tpo -c -o OgreBall-OgreBallApplication.o `test -f 'src/OgreBallApplication.cpp' || echo '$(srcdir)/'`src/OgreBallApplication.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-OgreBallApplication.Tpo $(DEPDIR)/OgreBall-OgreBallApplication.Po
#	$(AM_V_CXX)source='src/OgreBallApplication.cpp' object='OgreBall-OgreBallApplication.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-OgreBallApplication.o `test -f 'src/OgreBallApplication.cpp' || echo '$(srcdir)/'`src/OgreBallApplication.cpp

OgreBall-OgreBallApplication.obj: src/OgreBallApplication.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-OgreBallApplication.obj -MD -MP -MF $(DEPDIR)/OgreBall-OgreBallApplication.Tpo -c -o OgreBall-OgreBallApplication.obj `if test -f 'src/OgreBallApplication.cpp'; then $(CYGPATH_W) 'src/OgreBallApplication.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OgreBallApplication.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-OgreBallApplication.Tpo $(DEPDIR)/OgreBall-OgreBallApplication.Po
#	$(AM_V_CXX)source='src/OgreBallApplication.cpp' object='OgreBall-OgreBallApplication.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-OgreBallApplication.obj `if test -f 'src/OgreBallApplication.cpp'; then $(CYGPATH_W) 'src/OgreBallApplication.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OgreBallApplication.cpp'; fi`

OgreBall-Physics.o: src/Physics.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Physics.o -MD -MP -MF $(DEPDIR)/OgreBall-Physics.Tpo -c -o OgreBall-Physics.o `test -f 'src/Physics.cpp' || echo '$(srcdir)/'`src/Physics.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Physics.Tpo $(DEPDIR)/OgreBall-Physics.Po
#	$(AM_V_CXX)source='src/Physics.cpp' object='OgreBall-Physics.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Physics.o `test -f 'src/Physics.cpp' || echo '$(srcdir)/'`src/Physics.cpp

OgreBall-Physics.obj: src/Physics.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Physics.obj -MD -MP -MF $(DEPDIR)/OgreBall-Physics.Tpo -c -o OgreBall-Physics.obj `if test -f 'src/Physics.cpp'; then $(CYGPATH_W) 'src/Physics.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Physics.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Physics.Tpo $(DEPDIR)/OgreBall-Physics.Po
#	$(AM_V_CXX)source='src/Physics.cpp' object='OgreBall-Physics.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Physics.obj `if test -f 'src/Physics.cpp'; then $(CYGPATH_W) 'src/Physics.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Physics.cpp'; fi`

OgreBall-OgreMotionState.o: src/OgreMotionState.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-OgreMotionState.o -MD -MP -MF $(DEPDIR)/OgreBall-OgreMotionState.Tpo -c -o OgreBall-OgreMotionState.o `test -f 'src/OgreMotionState.cpp' || echo '$(srcdir)/'`src/OgreMotionState.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-OgreMotionState.Tpo $(DEPDIR)/OgreBall-OgreMotionState.Po
#	$(AM_V_CXX)source='src/OgreMotionState.cpp' object='OgreBall-OgreMotionState.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-OgreMotionState.o `test -f 'src/OgreMotionState.cpp' || echo '$(srcdir)/'`src/OgreMotionState.cpp

OgreBall-OgreMotionState.obj: src/OgreMotionState.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-OgreMotionState.obj -MD -MP -MF $(DEPDIR)/OgreBall-OgreMotionState.Tpo -c -o OgreBall-OgreMotionState.obj `if test -f 'src/OgreMotionState.cpp'; then $(CYGPATH_W) 'src/OgreMotionState.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OgreMotionState.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-OgreMotionState.Tpo $(DEPDIR)/OgreBall-OgreMotionState.Po
#	$(AM_V_CXX)source='src/OgreMotionState.cpp' object='OgreBall-OgreMotionState.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-OgreMotionState.obj `if test -f 'src/OgreMotionState.cpp'; then $(CYGPATH_W) 'src/OgreMotionState.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OgreMotionState.cpp'; fi`

OgreBall-GameObject.o: src/GameObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-GameObject.o -MD -MP -MF $(DEPDIR)/OgreBall-GameObject.Tpo -c -o OgreBall-GameObject.o `test -f 'src/GameObject.cpp' || echo '$(srcdir)/'`src/GameObject.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-GameObject.Tpo $(DEPDIR)/OgreBall-GameObject.Po
#	$(AM_V_CXX)source='src/GameObject.cpp' object='OgreBall-GameObject.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-GameObject.o `test -f 'src/GameObject.cpp' || echo '$(srcdir)/'`src/GameObject.cpp

OgreBall-GameObject.obj: src/GameObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-GameObject.obj -MD -MP -MF $(DEPDIR)/OgreBall-GameObject.Tpo -c -o OgreBall-GameObject.obj `if test -f 'src/GameObject.cpp'; then $(CYGPATH_W) 'src/GameObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/GameObject.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-GameObject.Tpo $(DEPDIR)/OgreBall-GameObject.Po
#	$(AM_V_CXX)source='src/GameObject.cpp' object='OgreBall-GameObject.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-GameObject.obj `if test -f 'src/GameObject.cpp'; then $(CYGPATH_W) 'src/GameObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/GameObject.cpp'; fi`

OgreBall-OgreBall.o: src/OgreBall.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-OgreBall.o -MD -MP -MF $(DEPDIR)/OgreBall-OgreBall.Tpo -c -o OgreBall-OgreBall.o `test -f 'src/OgreBall.cpp' || echo '$(srcdir)/'`src/OgreBall.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-OgreBall.Tpo $(DEPDIR)/OgreBall-OgreBall.Po
#	$(AM_V_CXX)source='src/OgreBall.cpp' object='OgreBall-OgreBall.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-OgreBall.o `test -f 'src/OgreBall.cpp' || echo '$(srcdir)/'`src/OgreBall.cpp

OgreBall-OgreBall.obj: src/OgreBall.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-OgreBall.obj -MD -MP -MF $(DEPDIR)/OgreBall-OgreBall.Tpo -c -o OgreBall-OgreBall.obj `if test -f 'src/OgreBall.cpp'; then $(CYGPATH_W) 'src/OgreBall.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OgreBall.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-OgreBall.Tpo $(DEPDIR)/OgreBall-OgreBall.Po
#	$(AM_V_CXX)source='src/OgreBall.cpp' object='OgreBall-OgreBall.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-OgreBall.obj `if test -f 'src/OgreBall.cpp'; then $(CYGPATH_W) 'src/OgreBall.cpp'; else $(CYGPATH_W) '$(srcdir)/src/OgreBall.cpp'; fi`

OgreBall-Plane.o: src/Plane.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Plane.o -MD -MP -MF $(DEPDIR)/OgreBall-Plane.Tpo -c -o OgreBall-Plane.o `test -f 'src/Plane.cpp' || echo '$(srcdir)/'`src/Plane.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Plane.Tpo $(DEPDIR)/OgreBall-Plane.Po
#	$(AM_V_CXX)source='src/Plane.cpp' object='OgreBall-Plane.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Plane.o `test -f 'src/Plane.cpp' || echo '$(srcdir)/'`src/Plane.cpp

OgreBall-Plane.obj: src/Plane.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Plane.obj -MD -MP -MF $(DEPDIR)/OgreBall-Plane.Tpo -c -o OgreBall-Plane.obj `if test -f 'src/Plane.cpp'; then $(CYGPATH_W) 'src/Plane.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Plane.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Plane.Tpo $(DEPDIR)/OgreBall-Plane.Po
#	$(AM_V_CXX)source='src/Plane.cpp' object='OgreBall-Plane.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Plane.obj `if test -f 'src/Plane.cpp'; then $(CYGPATH_W) 'src/Plane.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Plane.cpp'; fi`

OgreBall-LevelLoader.o: src/LevelLoader.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-LevelLoader.o -MD -MP -MF $(DEPDIR)/OgreBall-LevelLoader.Tpo -c -o OgreBall-LevelLoader.o `test -f 'src/LevelLoader.cpp' || echo '$(srcdir)/'`src/LevelLoader.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-LevelLoader.Tpo $(DEPDIR)/OgreBall-LevelLoader.Po
#	$(AM_V_CXX)source='src/LevelLoader.cpp' object='OgreBall-LevelLoader.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-LevelLoader.o `test -f 'src/LevelLoader.cpp' || echo '$(srcdir)/'`src/LevelLoader.cpp

OgreBall-LevelLoader.obj: src/LevelLoader.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-LevelLoader.obj -MD -MP -MF $(DEPDIR)/OgreBall-LevelLoader.Tpo -c -o OgreBall-LevelLoader.obj `if test -f 'src/LevelLoader.cpp'; then $(CYGPATH_W) 'src/LevelLoader.cpp'; else $(CYGPATH_W) '$(srcdir)/src/LevelLoader.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-LevelLoader.Tpo $(DEPDIR)/OgreBall-LevelLoader.Po
#	$(AM_V_CXX)source='src/LevelLoader.cpp' object='OgreBall-LevelLoader.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-LevelLoader.obj `if test -f 'src/LevelLoader.cpp'; then $(CYGPATH_W) 'src/LevelLoader.cpp'; else $(CYGPATH_W) '$(srcdir)/src/LevelLoader.cpp'; fi`

OgreBall-MeshObject.o: src/MeshObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MeshObject.o -MD -MP -MF $(DEPDIR)/OgreBall-MeshObject.Tpo -c -o OgreBall-MeshObject.o `test -f 'src/MeshObject.cpp' || echo '$(srcdir)/'`src/MeshObject.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MeshObject.Tpo $(DEPDIR)/OgreBall-MeshObject.Po
#	$(AM_V_CXX)source='src/MeshObject.cpp' object='OgreBall-MeshObject.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MeshObject.o `test -f 'src/MeshObject.cpp' || echo '$(srcdir)/'`src/MeshObject.cpp

OgreBall-MeshObject.obj: src/MeshObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MeshObject.obj -MD -MP -MF $(DEPDIR)/OgreBall-MeshObject.Tpo -c -o OgreBall-MeshObject.obj `if test -f 'src/MeshObject.cpp'; then $(CYGPATH_W) 'src/MeshObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/MeshObject.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MeshObject.Tpo $(DEPDIR)/OgreBall-MeshObject.Po
#	$(AM_V_CXX)source='src/MeshObject.cpp' object='OgreBall-MeshObject.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MeshObject.obj `if test -f 'src/MeshObject.cpp'; then $(CYGPATH_W) 'src/MeshObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/MeshObject.cpp'; fi`

OgreBall-MenuActivity.o: src/MenuActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MenuActivity.o -MD -MP -MF $(DEPDIR)/OgreBall-MenuActivity.Tpo -c -o OgreBall-MenuActivity.o `test -f 'src/MenuActivity.cpp' || echo '$(srcdir)/'`src/MenuActivity.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MenuActivity.Tpo $(DEPDIR)/OgreBall-MenuActivity.Po
#	$(AM_V_CXX)source='src/MenuActivity.cpp' object='OgreBall-MenuActivity.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MenuActivity.o `test -f 'src/MenuActivity.cpp' || echo '$(srcdir)/'`src/MenuActivity.cpp

OgreBall-MenuActivity.obj: src/MenuActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MenuActivity.obj -MD -MP -MF $(DEPDIR)/OgreBall-MenuActivity.Tpo -c -o OgreBall-MenuActivity.obj `if test -f 'src/MenuActivity.cpp'; then $(CYGPATH_W) 'src/MenuActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/MenuActivity.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MenuActivity.Tpo $(DEPDIR)/OgreBall-MenuActivity.Po
#	$(AM_V_CXX)source='src/MenuActivity.cpp' object='OgreBall-MenuActivity.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MenuActivity.obj `if test -f 'src/MenuActivity.cpp'; then $(CYGPATH_W) 'src/MenuActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/MenuActivity.cpp'; fi`

OgreBall-SinglePlayerActivity.o: src/SinglePlayerActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-SinglePlayerActivity.o -MD -MP -MF $(DEPDIR)/OgreBall-SinglePlayerActivity.Tpo -c -o OgreBall-SinglePlayerActivity.o `test -f 'src/SinglePlayerActivity.cpp' || echo '$(srcdir)/'`src/SinglePlayerActivity.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-SinglePlayerActivity.Tpo $(DEPDIR)/OgreBall-SinglePlayerActivity.Po
#	$(AM_V_CXX)source='src/SinglePlayerActivity.cpp' object='OgreBall-SinglePlayerActivity.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-SinglePlayerActivity.o `test -f 'src/SinglePlayerActivity.cpp' || echo '$(srcdir)/'`src/SinglePlayerActivity.cpp

OgreBall-SinglePlayerActivity.obj: src/SinglePlayerActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-SinglePlayerActivity.obj -MD -MP -MF $(DEPDIR)/OgreBall-SinglePlayerActivity.Tpo -c -o OgreBall-SinglePlayerActivity.obj `if test -f 'src/SinglePlayerActivity.cpp'; then $(CYGPATH_W) 'src/SinglePlayerActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/SinglePlayerActivity.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-SinglePlayerActivity.Tpo $(DEPDIR)/OgreBall-SinglePlayerActivity.Po
#	$(AM_V_CXX)source='src/SinglePlayerActivity.cpp' object='OgreBall-SinglePlayerActivity.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-SinglePlayerActivity.obj `if test -f 'src/SinglePlayerActivity.cpp'; then $(CYGPATH_W) 'src/SinglePlayerActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/SinglePlayerActivity.cpp'; fi`

OgreBall-Interpolator.o: src/Interpolator.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Interpolator.o -MD -MP -MF $(DEPDIR)/OgreBall-Interpolator.Tpo -c -o OgreBall-Interpolator.o `test -f 'src/Interpolator.cpp' || echo '$(srcdir)/'`src/Interpolator.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Interpolator.Tpo $(DEPDIR)/OgreBall-Interpolator.Po
#	$(AM_V_CXX)source='src/Interpolator.cpp' object='OgreBall-Interpolator.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Interpolator.o `test -f 'src/Interpolator.cpp' || echo '$(srcdir)/'`src/Interpolator.cpp

OgreBall-Interpolator.obj: src/Interpolator.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Interpolator.obj -MD -MP -MF $(DEPDIR)/OgreBall-Interpolator.Tpo -c -o OgreBall-Interpolator.obj `if test -f 'src/Interpolator.cpp'; then $(CYGPATH_W) 'src/Interpolator.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Interpolator.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Interpolator.Tpo $(DEPDIR)/OgreBall-Interpolator.Po
#	$(AM_V_CXX)source='src/Interpolator.cpp' object='OgreBall-Interpolator.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Interpolator.obj `if test -f 'src/Interpolator.cpp'; then $(CYGPATH_W) 'src/Interpolator.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Interpolator.cpp'; fi`

OgreBall-Collisions.o: src/Collisions.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Collisions.o -MD -MP -MF $(DEPDIR)/OgreBall-Collisions.Tpo -c -o OgreBall-Collisions.o `test -f 'src/Collisions.cpp' || echo '$(srcdir)/'`src/Collisions.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Collisions.Tpo $(DEPDIR)/OgreBall-Collisions.Po
#	$(AM_V_CXX)source='src/Collisions.cpp' object='OgreBall-Collisions.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Collisions.o `test -f 'src/Collisions.cpp' || echo '$(srcdir)/'`src/Collisions.cpp

OgreBall-Collisions.obj: src/Collisions.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Collisions.obj -MD -MP -MF $(DEPDIR)/OgreBall-Collisions.Tpo -c -o OgreBall-Collisions.obj `if test -f 'src/Collisions.cpp'; then $(CYGPATH_W) 'src/Collisions.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Collisions.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Collisions.Tpo $(DEPDIR)/OgreBall-Collisions.Po
#	$(AM_V_CXX)source='src/Collisions.cpp' object='OgreBall-Collisions.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Collisions.obj `if test -f 'src/Collisions.cpp'; then $(CYGPATH_W) 'src/Collisions.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Collisions.cpp'; fi`

OgreBall-GoalObject.o: src/GoalObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-GoalObject.o -MD -MP -MF $(DEPDIR)/OgreBall-GoalObject.Tpo -c -o OgreBall-GoalObject.o `test -f 'src/GoalObject.cpp' || echo '$(srcdir)/'`src/GoalObject.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-GoalObject.Tpo $(DEPDIR)/OgreBall-GoalObject.Po
#	$(AM_V_CXX)source='src/GoalObject.cpp' object='OgreBall-GoalObject.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-GoalObject.o `test -f 'src/GoalObject.cpp' || echo '$(srcdir)/'`src/GoalObject.cpp

OgreBall-GoalObject.obj: src/GoalObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-GoalObject.obj -MD -MP -MF $(DEPDIR)/OgreBall-GoalObject.Tpo -c -o OgreBall-GoalObject.obj `if test -f 'src/GoalObject.cpp'; then $(CYGPATH_W) 'src/GoalObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/GoalObject.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-GoalObject.Tpo $(DEPDIR)/OgreBall-GoalObject.Po
#	$(AM_V_CXX)source='src/GoalObject.cpp' object='OgreBall-GoalObject.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-GoalObject.obj `if test -f 'src/GoalObject.cpp'; then $(CYGPATH_W) 'src/GoalObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/GoalObject.cpp'; fi`

OgreBall-Collectible.o: src/Collectible.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Collectible.o -MD -MP -MF $(DEPDIR)/OgreBall-Collectible.Tpo -c -o OgreBall-Collectible.o `test -f 'src/Collectible.cpp' || echo '$(srcdir)/'`src/Collectible.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Collectible.Tpo $(DEPDIR)/OgreBall-Collectible.Po
#	$(AM_V_CXX)source='src/Collectible.cpp' object='OgreBall-Collectible.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Collectible.o `test -f 'src/Collectible.cpp' || echo '$(srcdir)/'`src/Collectible.cpp

OgreBall-Collectible.obj: src/Collectible.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Collectible.obj -MD -MP -MF $(DEPDIR)/OgreBall-Collectible.Tpo -c -o OgreBall-Collectible.obj `if test -f 'src/Collectible.cpp'; then $(CYGPATH_W) 'src/Collectible.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Collectible.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Collectible.Tpo $(DEPDIR)/OgreBall-Collectible.Po
#	$(AM_V_CXX)source='src/Collectible.cpp' object='OgreBall-Collectible.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Collectible.obj `if test -f 'src/Collectible.cpp'; then $(CYGPATH_W) 'src/Collectible.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Collectible.cpp'; fi`

OgreBall-LevelViewer.o: src/LevelViewer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-LevelViewer.o -MD -MP -MF $(DEPDIR)/OgreBall-LevelViewer.Tpo -c -o OgreBall-LevelViewer.o `test -f 'src/LevelViewer.cpp' || echo '$(srcdir)/'`src/LevelViewer.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-LevelViewer.Tpo $(DEPDIR)/OgreBall-LevelViewer.Po
#	$(AM_V_CXX)source='src/LevelViewer.cpp' object='OgreBall-LevelViewer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-LevelViewer.o `test -f 'src/LevelViewer.cpp' || echo '$(srcdir)/'`src/LevelViewer.cpp

OgreBall-LevelViewer.obj: src/LevelViewer.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-LevelViewer.obj -MD -MP -MF $(DEPDIR)/OgreBall-LevelViewer.Tpo -c -o OgreBall-LevelViewer.obj `if test -f 'src/LevelViewer.cpp'; then $(CYGPATH_W) 'src/LevelViewer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/LevelViewer.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-LevelViewer.Tpo $(DEPDIR)/OgreBall-LevelViewer.Po
#	$(AM_V_CXX)source='src/LevelViewer.cpp' object='OgreBall-LevelViewer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-LevelViewer.obj `if test -f 'src/LevelViewer.cpp'; then $(CYGPATH_W) 'src/LevelViewer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/LevelViewer.cpp'; fi`

OgreBall-DecorativeObject.o: src/DecorativeObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-DecorativeObject.o -MD -MP -MF $(DEPDIR)/OgreBall-DecorativeObject.Tpo -c -o OgreBall-DecorativeObject.o `test -f 'src/DecorativeObject.cpp' || echo '$(srcdir)/'`src/DecorativeObject.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-DecorativeObject.Tpo $(DEPDIR)/OgreBall-DecorativeObject.Po
#	$(AM_V_CXX)source='src/DecorativeObject.cpp' object='OgreBall-DecorativeObject.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-DecorativeObject.o `test -f 'src/DecorativeObject.cpp' || echo '$(srcdir)/'`src/DecorativeObject.cpp

OgreBall-DecorativeObject.obj: src/DecorativeObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-DecorativeObject.obj -MD -MP -MF $(DEPDIR)/OgreBall-DecorativeObject.Tpo -c -o OgreBall-DecorativeObject.obj `if test -f 'src/DecorativeObject.cpp'; then $(CYGPATH_W) 'src/DecorativeObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/DecorativeObject.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-DecorativeObject.Tpo $(DEPDIR)/OgreBall-DecorativeObject.Po
#	$(AM_V_CXX)source='src/DecorativeObject.cpp' object='OgreBall-DecorativeObject.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-DecorativeObject.obj `if test -f 'src/DecorativeObject.cpp'; then $(CYGPATH_W) 'src/DecorativeObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/DecorativeObject.cpp'; fi`

OgreBall-CameraObject.o: src/CameraObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-CameraObject.o -MD -MP -MF $(DEPDIR)/OgreBall-CameraObject.Tpo -c -o OgreBall-CameraObject.o `test -f 'src/CameraObject.cpp' || echo '$(srcdir)/'`src/CameraObject.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-CameraObject.Tpo $(DEPDIR)/OgreBall-CameraObject.Po
#	$(AM_V_CXX)source='src/CameraObject.cpp' object='OgreBall-CameraObject.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-CameraObject.o `test -f 'src/CameraObject.cpp' || echo '$(srcdir)/'`src/CameraObject.cpp

OgreBall-CameraObject.obj: src/CameraObject.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-CameraObject.obj -MD -MP -MF $(DEPDIR)/OgreBall-CameraObject.Tpo -c -o OgreBall-CameraObject.obj `if test -f 'src/CameraObject.cpp'; then $(CYGPATH_W) 'src/CameraObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/CameraObject.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-CameraObject.Tpo $(DEPDIR)/OgreBall-CameraObject.Po
#	$(AM_V_CXX)source='src/CameraObject.cpp' object='OgreBall-CameraObject.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-CameraObject.obj `if test -f 'src/CameraObject.cpp'; then $(CYGPATH_W) 'src/CameraObject.cpp'; else $(CYGPATH_W) '$(srcdir)/src/CameraObject.cpp'; fi`

OgreBall-Sounds.o: src/Sounds.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Sounds.o -MD -MP -MF $(DEPDIR)/OgreBall-Sounds.Tpo -c -o OgreBall-Sounds.o `test -f 'src/Sounds.cpp' || echo '$(srcdir)/'`src/Sounds.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Sounds.Tpo $(DEPDIR)/OgreBall-Sounds.Po
#	$(AM_V_CXX)source='src/Sounds.cpp' object='OgreBall-Sounds.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Sounds.o `test -f 'src/Sounds.cpp' || echo '$(srcdir)/'`src/Sounds.cpp

OgreBall-Sounds.obj: src/Sounds.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Sounds.obj -MD -MP -MF $(DEPDIR)/OgreBall-Sounds.Tpo -c -o OgreBall-Sounds.obj `if test -f 'src/Sounds.cpp'; then $(CYGPATH_W) 'src/Sounds.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Sounds.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Sounds.Tpo $(DEPDIR)/OgreBall-Sounds.Po
#	$(AM_V_CXX)source='src/Sounds.cpp' object='OgreBall-Sounds.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Sounds.obj `if test -f 'src/Sounds.cpp'; then $(CYGPATH_W) 'src/Sounds.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Sounds.cpp'; fi`

OgreBall-Collidable.o: src/Collidable.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Collidable.o -MD -MP -MF $(DEPDIR)/OgreBall-Collidable.Tpo -c -o OgreBall-Collidable.o `test -f 'src/Collidable.cpp' || echo '$(srcdir)/'`src/Collidable.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Collidable.Tpo $(DEPDIR)/OgreBall-Collidable.Po
#	$(AM_V_CXX)source='src/Collidable.cpp' object='OgreBall-Collidable.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Collidable.o `test -f 'src/Collidable.cpp' || echo '$(srcdir)/'`src/Collidable.cpp

OgreBall-Collidable.obj: src/Collidable.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Collidable.obj -MD -MP -MF $(DEPDIR)/OgreBall-Collidable.Tpo -c -o OgreBall-Collidable.obj `if test -f 'src/Collidable.cpp'; then $(CYGPATH_W) 'src/Collidable.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Collidable.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Collidable.Tpo $(DEPDIR)/OgreBall-Collidable.Po
#	$(AM_V_CXX)source='src/Collidable.cpp' object='OgreBall-Collidable.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Collidable.obj `if test -f 'src/Collidable.cpp'; then $(CYGPATH_W) 'src/Collidable.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Collidable.cpp'; fi`

OgreBall-ClientPlayerActivity.o: src/ClientPlayerActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-ClientPlayerActivity.o -MD -MP -MF $(DEPDIR)/OgreBall-ClientPlayerActivity.Tpo -c -o OgreBall-ClientPlayerActivity.o `test -f 'src/ClientPlayerActivity.cpp' || echo '$(srcdir)/'`src/ClientPlayerActivity.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-ClientPlayerActivity.Tpo $(DEPDIR)/OgreBall-ClientPlayerActivity.Po
#	$(AM_V_CXX)source='src/ClientPlayerActivity.cpp' object='OgreBall-ClientPlayerActivity.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-ClientPlayerActivity.o `test -f 'src/ClientPlayerActivity.cpp' || echo '$(srcdir)/'`src/ClientPlayerActivity.cpp

OgreBall-ClientPlayerActivity.obj: src/ClientPlayerActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-ClientPlayerActivity.obj -MD -MP -MF $(DEPDIR)/OgreBall-ClientPlayerActivity.Tpo -c -o OgreBall-ClientPlayerActivity.obj `if test -f 'src/ClientPlayerActivity.cpp'; then $(CYGPATH_W) 'src/ClientPlayerActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ClientPlayerActivity.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-ClientPlayerActivity.Tpo $(DEPDIR)/OgreBall-ClientPlayerActivity.Po
#	$(AM_V_CXX)source='src/ClientPlayerActivity.cpp' object='OgreBall-ClientPlayerActivity.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-ClientPlayerActivity.obj `if test -f 'src/ClientPlayerActivity.cpp'; then $(CYGPATH_W) 'src/ClientPlayerActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/ClientPlayerActivity.cpp'; fi`

OgreBall-HostPlayerActivity.o: src/HostPlayerActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-HostPlayerActivity.o -MD -MP -MF $(DEPDIR)/OgreBall-HostPlayerActivity.Tpo -c -o OgreBall-HostPlayerActivity.o `test -f 'src/HostPlayerActivity.cpp' || echo '$(srcdir)/'`src/HostPlayerActivity.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-HostPlayerActivity.Tpo $(DEPDIR)/OgreBall-HostPlayerActivity.Po
#	$(AM_V_CXX)source='src/HostPlayerActivity.cpp' object='OgreBall-HostPlayerActivity.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-HostPlayerActivity.o `test -f 'src/HostPlayerActivity.cpp' || echo '$(srcdir)/'`src/HostPlayerActivity.cpp

OgreBall-HostPlayerActivity.obj: src/HostPlayerActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-HostPlayerActivity.obj -MD -MP -MF $(DEPDIR)/OgreBall-HostPlayerActivity.Tpo -c -o OgreBall-HostPlayerActivity.obj `if test -f 'src/HostPlayerActivity.cpp'; then $(CYGPATH_W) 'src/HostPlayerActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/HostPlayerActivity.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-HostPlayerActivity.Tpo $(DEPDIR)/OgreBall-HostPlayerActivity.Po
#	$(AM_V_CXX)source='src/HostPlayerActivity.cpp' object='OgreBall-HostPlayerActivity.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-HostPlayerActivity.obj `if test -f 'src/HostPlayerActivity.cpp'; then $(CYGPATH_W) 'src/HostPlayerActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/HostPlayerActivity.cpp'; fi`

OgreBall-Networking.o: src/Networking.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Networking.o -MD -MP -MF $(DEPDIR)/OgreBall-Networking.Tpo -c -o OgreBall-Networking.o `test -f 'src/Networking.cpp' || echo '$(srcdir)/'`src/Networking.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Networking.Tpo $(DEPDIR)/OgreBall-Networking.Po
#	$(AM_V_CXX)source='src/Networking.cpp' object='OgreBall-Networking.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Networking.o `test -f 'src/Networking.cpp' || echo '$(srcdir)/'`src/Networking.cpp

OgreBall-Networking.obj: src/Networking.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-Networking.obj -MD -MP -MF $(DEPDIR)/OgreBall-Networking.Tpo -c -o OgreBall-Networking.obj `if test -f 'src/Networking.cpp'; then $(CYGPATH_W) 'src/Networking.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Networking.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-Networking.Tpo $(DEPDIR)/OgreBall-Networking.Po
#	$(AM_V_CXX)source='src/Networking.cpp' object='OgreBall-Networking.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-Networking.obj `if test -f 'src/Networking.cpp'; then $(CYGPATH_W) 'src/Networking.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Networking.cpp'; fi`

OgreBall-common.o: src/common.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-common.o -MD -MP -MF $(DEPDIR)/OgreBall-common.Tpo -c -o OgreBall-common.o `test -f 'src/common.cpp' || echo '$(srcdir)/'`src/common.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-common.Tpo $(DEPDIR)/OgreBall-common.Po
#	$(AM_V_CXX)source='src/common.cpp' object='OgreBall-common.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-common.o `test -f 'src/common.cpp' || echo '$(srcdir)/'`src/common.cpp

OgreBall-common.obj: src/common.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-common.obj -MD -MP -MF $(DEPDIR)/OgreBall-common.Tpo -c -o OgreBall-common.obj `if test -f 'src/common.cpp'; then $(CYGPATH_W) 'src/common.cpp'; else $(CYGPATH_W) '$(srcdir)/src/common.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-common.Tpo $(DEPDIR)/OgreBall-common.Po
#	$(AM_V_CXX)source='src/common.cpp' object='OgreBall-common.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-common.obj `if test -f 'src/common.cpp'; then $(CYGPATH_W) 'src/common.cpp'; else $(CYGPATH_W) '$(srcdir)/src/common.cpp'; fi`

OgreBall-BaseMultiActivity.o: src/BaseMultiActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-BaseMultiActivity.o -MD -MP -MF $(DEPDIR)/OgreBall-BaseMultiActivity.Tpo -c -o OgreBall-BaseMultiActivity.o `test -f 'src/BaseMultiActivity.cpp' || echo '$(srcdir)/'`src/BaseMultiActivity.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-BaseMultiActivity.Tpo $(DEPDIR)/OgreBall-BaseMultiActivity.Po
#	$(AM_V_CXX)source='src/BaseMultiActivity.cpp' object='OgreBall-BaseMultiActivity.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-BaseMultiActivity.o `test -f 'src/BaseMultiActivity.cpp' || echo '$(srcdir)/'`src/BaseMultiActivity.cpp

OgreBall-BaseMultiActivity.obj: src/BaseMultiActivity.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-BaseMultiActivity.obj -MD -MP -MF $(DEPDIR)/OgreBall-BaseMultiActivity.Tpo -c -o OgreBall-BaseMultiActivity.obj `if test -f 'src/BaseMultiActivity.cpp'; then $(CYGPATH_W) 'src/BaseMultiActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/BaseMultiActivity.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-BaseMultiActivity.Tpo $(DEPDIR)/OgreBall-BaseMultiActivity.Po
#	$(AM_V_CXX)source='src/BaseMultiActivity.cpp' object='OgreBall-BaseMultiActivity.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-BaseMultiActivity.obj `if test -f 'src/BaseMultiActivity.cpp'; then $(CYGPATH_W) 'src/BaseMultiActivity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/BaseMultiActivity.cpp'; fi`

OgreBall-SelectorHelper.o: src/SelectorHelper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-SelectorHelper.o -MD -MP -MF $(DEPDIR)/OgreBall-SelectorHelper.Tpo -c -o OgreBall-SelectorHelper.o `test -f 'src/SelectorHelper.cpp' || echo '$(srcdir)/'`src/SelectorHelper.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-SelectorHelper.Tpo $(DEPDIR)/OgreBall-SelectorHelper.Po
#	$(AM_V_CXX)source='src/SelectorHelper.cpp' object='OgreBall-SelectorHelper.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-SelectorHelper.o `test -f 'src/SelectorHelper.cpp' || echo '$(srcdir)/'`src/SelectorHelper.cpp

OgreBall-SelectorHelper.obj: src/SelectorHelper.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-SelectorHelper.obj -MD -MP -MF $(DEPDIR)/OgreBall-SelectorHelper.Tpo -c -o OgreBall-SelectorHelper.obj `if test -f 'src/SelectorHelper.cpp'; then $(CYGPATH_W) 'src/SelectorHelper.cpp'; else $(CYGPATH_W) '$(srcdir)/src/SelectorHelper.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-SelectorHelper.Tpo $(DEPDIR)/OgreBall-SelectorHelper.Po
#	$(AM_V_CXX)source='src/SelectorHelper.cpp' object='OgreBall-SelectorHelper.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-SelectorHelper.obj `if test -f 'src/SelectorHelper.cpp'; then $(CYGPATH_W) 'src/SelectorHelper.cpp'; else $(CYGPATH_W) '$(srcdir)/src/SelectorHelper.cpp'; fi`

OgreBall-MovableTextOverlay.o: libs/MovableTextOverlay.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MovableTextOverlay.o -MD -MP -MF $(DEPDIR)/OgreBall-MovableTextOverlay.Tpo -c -o OgreBall-MovableTextOverlay.o `test -f 'libs/MovableTextOverlay.cpp' || echo '$(srcdir)/'`libs/MovableTextOverlay.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MovableTextOverlay.Tpo $(DEPDIR)/OgreBall-MovableTextOverlay.Po
#	$(AM_V_CXX)source='libs/MovableTextOverlay.cpp' object='OgreBall-MovableTextOverlay.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MovableTextOverlay.o `test -f 'libs/MovableTextOverlay.cpp' || echo '$(srcdir)/'`libs/MovableTextOverlay.cpp

OgreBall-MovableTextOverlay.obj: libs/MovableTextOverlay.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-MovableTextOverlay.obj -MD -MP -MF $(DEPDIR)/OgreBall-MovableTextOverlay.Tpo -c -o OgreBall-MovableTextOverlay.obj `if test -f 'libs/MovableTextOverlay.cpp'; then $(CYGPATH_W) 'libs/MovableTextOverlay.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/MovableTextOverlay.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-MovableTextOverlay.Tpo $(DEPDIR)/OgreBall-MovableTextOverlay.Po
#	$(AM_V_CXX)source='libs/MovableTextOverlay.cpp' object='OgreBall-MovableTextOverlay.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-MovableTextOverlay.obj `if test -f 'libs/MovableTextOverlay.cpp'; then $(CYGPATH_W) 'libs/MovableTextOverlay.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/MovableTextOverlay.cpp'; fi`

OgreBall-RectLayoutManager.o: libs/RectLayoutManager.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-RectLayoutManager.o -MD -MP -MF $(DEPDIR)/OgreBall-RectLayoutManager.Tpo -c -o OgreBall-RectLayoutManager.o `test -f 'libs/RectLayoutManager.cpp' || echo '$(srcdir)/'`libs/RectLayoutManager.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-RectLayoutManager.Tpo $(DEPDIR)/OgreBall-RectLayoutManager.Po
#	$(AM_V_CXX)source='libs/RectLayoutManager.cpp' object='OgreBall-RectLayoutManager.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-RectLayoutManager.o `test -f 'libs/RectLayoutManager.cpp' || echo '$(srcdir)/'`libs/RectLayoutManager.cpp

OgreBall-RectLayoutManager.obj: libs/RectLayoutManager.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-RectLayoutManager.obj -MD -MP -MF $(DEPDIR)/OgreBall-RectLayoutManager.Tpo -c -o OgreBall-RectLayoutManager.obj `if test -f 'libs/RectLayoutManager.cpp'; then $(CYGPATH_W) 'libs/RectLayoutManager.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/RectLayoutManager.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-RectLayoutManager.Tpo $(DEPDIR)/OgreBall-RectLayoutManager.Po
#	$(AM_V_CXX)source='libs/RectLayoutManager.cpp' object='OgreBall-RectLayoutManager.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-RectLayoutManager.obj `if test -f 'libs/RectLayoutManager.cpp'; then $(CYGPATH_W) 'libs/RectLayoutManager.cpp'; else $(CYGPATH_W) '$(srcdir)/libs/RectLayoutManager.cpp'; fi`

OgreBall-GamecubeController.o: src/GamecubeController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-GamecubeController.o -MD -MP -MF $(DEPDIR)/OgreBall-GamecubeController.Tpo -c -o OgreBall-GamecubeController.o `test -f 'src/GamecubeController.cpp' || echo '$(srcdir)/'`src/GamecubeController.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-GamecubeController.Tpo $(DEPDIR)/OgreBall-GamecubeController.Po
#	$(AM_V_CXX)source='src/GamecubeController.cpp' object='OgreBall-GamecubeController.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-GamecubeController.o `test -f 'src/GamecubeController.cpp' || echo '$(srcdir)/'`src/GamecubeController.cpp

OgreBall-GamecubeController.obj: src/GamecubeController.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -MT OgreBall-GamecubeController.obj -MD -MP -MF $(DEPDIR)/OgreBall-GamecubeController.Tpo -c -o OgreBall-GamecubeController.obj `if test -f 'src/GamecubeController.cpp'; then $(CYGPATH_W) 'src/GamecubeController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/GamecubeController.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/OgreBall-GamecubeController.Tpo $(DEPDIR)/OgreBall-GamecubeController.Po
#	$(AM_V_CXX)source='src/GamecubeController.cpp' object='OgreBall-GamecubeController.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(OgreBall_CPPFLAGS) $(CPPFLAGS) $(OgreBall_CXXFLAGS) $(CXXFLAGS) -c -o OgreBall-GamecubeController.obj `if test -f 'src/GamecubeController.cpp'; then $(CYGPATH_W) 'src/GamecubeController.cpp'; else $(CYGPATH_W) '$(srcdir)/src/GamecubeController.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic clean-libtool \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
